### PR TITLE
Update to SPT 3.9.0

### PR DESCRIPTION
**Pull request by hel0t**

### CODE REVIEW

**Comment by hel0t** [comment]
Need to do server mod, forgot to include that

**Comment by Skwizzy** [comment]
@hel0t Oh awesome thanks for this! I can take a look in a few hours after work and get this merged/released

**Comment by Skwizzy** [comment]
Changes look good to me! Merging it into the 3.9.0 branch to do some final testing before adding the release

**Comment by hel0t** [comment]
Thanks! Appreciate it :D

**Pull request merged**
